apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-testing-ui
  template:
    metadata:
      labels:
        app: api-testing-ui
    spec:
      containers:
      - name: api-testing-ui
        image: api-testing-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: DEBUG
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/api-testing
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  selector:
    app: api-testing-ui
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 