apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-testing-ui
  namespace: nodejs
  labels:
    app: api-testing-ui
    version: "1.0.7"
    environment: production
    lumigo.auto-trace: "false"  # <-- No injection will take place
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-testing-ui
  template:
    metadata:
      labels:
        app: api-testing-ui
        version: "1.0.7"
        environment: production
    spec:
      containers:
      - name: api-testing-ui
        image: api-testing-ui:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
        - name: metrics
          containerPort: 3001
        env:
        # Application Configuration
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "debug"
        - name: MONGODB_URI
          value: mongodb://mongodb.nodejs.svc.cluster.local:27017/api-testing
        
        # HTTP Logging Configuration
        - name: HTTP_LOGGING_ENABLED
          value: "true"
        
        # OpenTelemetry Basic Configuration
        - name: OTEL_ENABLED
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "api-testing-ui"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.7"
        - name: OTEL_LOG_LEVEL
          value: "debug"
        
        # Sampling Configuration
        - name: OTEL_SAMPLING_RATE
          value: "1.0"
        - name: OTEL_TRACES_SAMPLER
          value: "traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "1.0"
        
        # OTLP Exporter Configuration
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://ga-otlp.lumigo-tracer-edge.golumigo.com"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=LumigoToken t_f8f7b905da964eef89261"
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: "gzip"
        - name: OTEL_EXPORT_TIMEOUT
          value: "30000"
        - name: OTEL_EXPORT_CONCURRENCY
          value: "1"
        
        # Retry Configuration
        - name: OTEL_RETRY_INITIAL_DELAY
          value: "1000"
        - name: OTEL_RETRY_MAX_DELAY
          value: "5000"
        - name: OTEL_RETRY_MAX_ATTEMPTS
          value: "5"
        - name: OTEL_RETRY_BACKOFF_MULTIPLIER
          value: "1.5"
        
        # Batch Processor Configuration
        - name: OTEL_BSP_MAX_QUEUE_SIZE
          value: "2048"
        - name: OTEL_BSP_SCHEDULE_DELAY
          value: "1000"
        - name: OTEL_BSP_EXPORT_TIMEOUT
          value: "30000"
        - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
          value: "512"
        
        # Instrumentation Control
        - name: OTEL_INSTRUMENT_HTTP
          value: "true"
        - name: OTEL_INSTRUMENT_EXPRESS
          value: "true"
        - name: OTEL_INSTRUMENT_MONGODB
          value: "true"
        
        # Propagation Configuration
        - name: OTEL_PROPAGATORS
          value: "b3"
        
        # Metrics Configuration
        - name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
          value: "true"
        
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: logs
        emptyDir: {}
      - name: config
        configMap:
          name: api-testing-ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-testing-ui
  namespace: nodejs
  labels:
    app: api-testing-ui
    version: "1.0.7"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: api-testing-ui
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: metrics
    port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-testing-ui-config
  namespace: nodejs
  labels:
    app: api-testing-ui
    version: "1.0.7"
data:
  NODE_ENV: "production"
  LOG_LEVEL: "debug"
  HTTP_LOGGING_ENABLED: "true"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "api-testing-ui"
  OTEL_SERVICE_VERSION: "1.0.7"
  OTEL_LOG_LEVEL: "debug"
  OTEL_SAMPLING_RATE: "0.2"
  OTEL_TRACES_SAMPLER: "traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.2"
  OTEL_EXPORTER_OTLP_COMPRESSION: "gzip"
  OTEL_EXPORT_TIMEOUT: "30000"
  OTEL_EXPORT_CONCURRENCY: "1"
  OTEL_RETRY_INITIAL_DELAY: "1000"
  OTEL_RETRY_MAX_DELAY: "5000"
  OTEL_RETRY_MAX_ATTEMPTS: "5"
  OTEL_RETRY_BACKOFF_MULTIPLIER: "1.5"
  OTEL_BSP_MAX_QUEUE_SIZE: "2048"
  OTEL_BSP_SCHEDULE_DELAY: "1000"
  OTEL_BSP_EXPORT_TIMEOUT: "30000"
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: "512"
  OTEL_INSTRUMENT_HTTP: "true"
  OTEL_INSTRUMENT_EXPRESS: "true"
  OTEL_INSTRUMENT_MONGODB: "true"
  OTEL_PROPAGATORS: "b3"
  OTEL_EXPORTER_OTLP_METRICS_ENABLED: "true" 