apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-testing-ui
  template:
    metadata:
      labels:
        app: api-testing-ui
    spec:
      containers:
      - name: api-testing-ui
        image: api-testing-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: DEBUG
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/api-testing
        # OpenTelemetry Configuration
        - name: OTEL_ENABLED
          value: "true"
        - name: OTEL_SAMPLING_RATE
          value: "1.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          # value: "https://ga-otlp.lumigo-tracer-edge.golumigo.com"
          value: "http://lumigo-lumigo-operator-telemetry-proxy-service.lumigo-system.svc.cluster.local/v1/traces"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=LumigoToken t_f8f7b905da964eef89261"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
          value: "false"
        - name: OTEL_SERVICE_NAME
          value: "api-testing-ui"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "1.0"
        - name: OTEL_PROPAGATORS
          value: "b3"
        - name: OTEL_LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  selector:
    app: api-testing-ui
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 