apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-testing-ui
  template:
    metadata:
      labels:
        app: api-testing-ui
    spec:
      containers:
      - name: api-testing-ui
        image: api-testing-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb.nodejs.svc.cluster.local:27017/api-testing"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: api-testing-ui
  namespace: nodejs
spec:
  selector:
    app: api-testing-ui
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer 