apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins: ["*"]
            max_request_body_size: 10_000_000
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              static_configs:
                - targets: ['0.0.0.0:8888']

    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
        spike_limit_mib: 512
      resource:
        attributes:
          - key: service.name
            value: "api-testing-tool"
            action: upsert

    exporters:
      debug:
        verbosity: detailed
      logging:
        loglevel: debug
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "otel"
        const_labels:
          label1: value1
        send_timestamps: true
        metric_expiration: 180m

    service:
      telemetry:
        logs:
          level: debug
          development: true
          encoding: "console"
        metrics:
          level: "detailed"
          address: "0.0.0.0:8888"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [debug, logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [debug, logging, prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [debug, logging, loki]