apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-testing-ui
  namespace: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api-testing-ui
  template:
    metadata:
      labels:
        app: python-api-testing-ui
    spec:
      containers:
      - name: python-api-testing-ui
        image: barrysolomon/python-api-testing-ui:latest
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb.python.svc.cluster.local:27017/api-testing
        - name: LOG_LEVEL
          value: INFO
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-testing-ui
  namespace: python
spec:
  selector:
    app: python-api-testing-ui
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer 